### PR TITLE
Fix actions dropdown on the datagrid

### LINKED ISSUE #833: Reporting 3 Bugs !
**Describe the bug**
1. The drop down menu under actions doesn't show up.
2. Can't Delete invoices !
3. Payment through Credit or cash or any give error output: "500 Internal Server Error"

**To Reproduce**
1. Go to 'List Invoices'
2. Click on '... Drop down menu'
3. See error

**To Reproduce**
1. Go to 'List Invoices'
2. Click on 'Select desired invoices'
3. Click on 'Delete'
4.Click on 'OK'
5. See error 'Deletion doesn't happened!

**To Reproduce**
1. Go to 'List Invoices'
2. Click on 'Select desired invoices which is on pending'
3. Click on 'Pay now'
4. Click on 'Payment Method / chose Credit'
5. Click 'Pay Now'
5. See error 'The server returned a "500 Internal Server Error".!

The whole testing was done under latest version of 2.2.3
Installed by using `docker run --name solidinvoice -p <APP_PORT>:80 -d solidinvoice/solidinvoice:<VERSION>-full`

Search function under List invoices doesn't seem to work!
To reproduce it you simply create an invoice and search by client name the output will be "no data"

**Screenshots**
brave_MdM0fdZuKe
brave_uGySaGwb1C
brave_5bLfih1Xgl

### PR DESCRIPTION
**Pull request by pierredup**
Partially fixes #833

### CODE REVIEW

**Comment by davi2td** [comment]
Hi, is "overflow: visible;"  added to src/DataGridBundle/Resources/public/scss/grid.scss
the only thing needed? cause I added that to my running 2.2.3-full to no avail, still not working.
Thanks
-Tom

**Comment by pierredup** [comment]
@davi1td When making any changes to the scss file, the assets needs to be compiled again. You would need to install [Yarn](https://yarnpkg.com/getting-started/install), then in the root directory run `yarn install` followed by `yarn build`. This should build all the assets again and the changes should then be visible in the app

**Comment by davi2td** [comment]
I might just wait till released and on docker, any idea when that might be?

**Comment by pierredup** [comment]
Hopefully in the next week or two. There is one more bugfix that I would like to get into the next release

**Pull request merged**
